# Generated by Django 3.1.3 on 2020-11-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
